title: pin's
email: spinute.pages@gmail.com
descript: >
  This is personal homepage for spinute(堀江 慧 Horie Satoru).<br>
  I'm in the University oy Tokyo.(
  <a hrey="http://www.c.u-tokyo.ac.jp/eng_site/">the Graduate school of Arts and Sciences</a>,
  <a href="http://system.c.u-tokyo.ac.jp/index_e.html">Department of General Systems Studies</a>,
  <a href="http://metahack.org">Fukunaga Alex lab.</a>
  )<br>
  <div align='right'>&copy;2015&nbsp;spinute</div>

baseurl: ""
url: "http://spinute.org"
twitter_username: spinute
github_username:  spinute

# Build settings
markdown: kramdown
