# This file is *NOT* reloaded automatically when you use 'jekyll serve'.
# If you change this file, please restart the server process.

# Site settings
title: Pin's
email: spinutids@gmail.com
descript: >
  This is a website of spinute(Horie Satoru, Pin).<br>
  <div align='right'>&copy;2016&nbsp;spinute</div>
baseurl: ""
url: "http://spinute.org"
twitter_username: spinute
github_username:  spinute

# Build settings
markdown: kramdown
