# Site settings
title: pin's
email: spinute.pages@gmail.com
descript: > 
  This is personal homepage for spinute(堀江 慧 Horie Satoru).<br>
  I'm in the University oy Tokyo, 
  Faculty of Arts and Science,
  Informatic Science major,
  undergraduate student.<br>
  <a href="http://metahack.org">Fukunaga Alex lab.</a><br>
  <div align='right'>&copy;2014&nbsp;spinute</div>

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.spinute.org" # the base hostname & protocol for your site
twitter_username: spinute
github_username:  spinute

# Build settings
markdown: kramdown
